name: Benedikt Sebastian
favicon: null
layout_spectrum: 0.6986725036986172
typography_spectrum: 0.971643885364756
title: Benedikt Sebastian
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8612623058725148
  lightness: 0.9256250211037695
  saturation: 0.973861045204103
  rhythmicContrast: 0.35399952135048807
purpose: []
